/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "otasrvr.pb-c.h"
void   address_struct__init
                     (AddressStruct         *message)
{
  static AddressStruct init_value = ADDRESS_STRUCT__INIT;
  *message = init_value;
}
size_t address_struct__get_packed_size
                     (const AddressStruct *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &address_struct__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t address_struct__pack
                     (const AddressStruct *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &address_struct__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t address_struct__pack_to_buffer
                     (const AddressStruct *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &address_struct__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AddressStruct *
       address_struct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AddressStruct *)
     protobuf_c_message_unpack (&address_struct__descriptor,
                                allocator, len, data);
}
void   address_struct__free_unpacked
                     (AddressStruct *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &address_struct__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_zigbee_generic_cnf__init
                     (OtaZigbeeGenericCnf         *message)
{
  static OtaZigbeeGenericCnf init_value = OTA_ZIGBEE_GENERIC_CNF__INIT;
  *message = init_value;
}
size_t ota_zigbee_generic_cnf__get_packed_size
                     (const OtaZigbeeGenericCnf *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_zigbee_generic_cnf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_zigbee_generic_cnf__pack
                     (const OtaZigbeeGenericCnf *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_zigbee_generic_cnf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_zigbee_generic_cnf__pack_to_buffer
                     (const OtaZigbeeGenericCnf *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_zigbee_generic_cnf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaZigbeeGenericCnf *
       ota_zigbee_generic_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaZigbeeGenericCnf *)
     protobuf_c_message_unpack (&ota_zigbee_generic_cnf__descriptor,
                                allocator, len, data);
}
void   ota_zigbee_generic_cnf__free_unpacked
                     (OtaZigbeeGenericCnf *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_zigbee_generic_cnf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_zigbee_generic_rsp_ind__init
                     (OtaZigbeeGenericRspInd         *message)
{
  static OtaZigbeeGenericRspInd init_value = OTA_ZIGBEE_GENERIC_RSP_IND__INIT;
  *message = init_value;
}
size_t ota_zigbee_generic_rsp_ind__get_packed_size
                     (const OtaZigbeeGenericRspInd *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_zigbee_generic_rsp_ind__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_zigbee_generic_rsp_ind__pack
                     (const OtaZigbeeGenericRspInd *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_zigbee_generic_rsp_ind__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_zigbee_generic_rsp_ind__pack_to_buffer
                     (const OtaZigbeeGenericRspInd *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_zigbee_generic_rsp_ind__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaZigbeeGenericRspInd *
       ota_zigbee_generic_rsp_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaZigbeeGenericRspInd *)
     protobuf_c_message_unpack (&ota_zigbee_generic_rsp_ind__descriptor,
                                allocator, len, data);
}
void   ota_zigbee_generic_rsp_ind__free_unpacked
                     (OtaZigbeeGenericRspInd *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_zigbee_generic_rsp_ind__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_update_image_registeration_req__init
                     (OtaUpdateImageRegisterationReq         *message)
{
  static OtaUpdateImageRegisterationReq init_value = OTA_UPDATE_IMAGE_REGISTERATION_REQ__INIT;
  *message = init_value;
}
size_t ota_update_image_registeration_req__get_packed_size
                     (const OtaUpdateImageRegisterationReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_image_registeration_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_update_image_registeration_req__pack
                     (const OtaUpdateImageRegisterationReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_image_registeration_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_update_image_registeration_req__pack_to_buffer
                     (const OtaUpdateImageRegisterationReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_image_registeration_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaUpdateImageRegisterationReq *
       ota_update_image_registeration_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaUpdateImageRegisterationReq *)
     protobuf_c_message_unpack (&ota_update_image_registeration_req__descriptor,
                                allocator, len, data);
}
void   ota_update_image_registeration_req__free_unpacked
                     (OtaUpdateImageRegisterationReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_image_registeration_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_update_enable_req__init
                     (OtaUpdateEnableReq         *message)
{
  static OtaUpdateEnableReq init_value = OTA_UPDATE_ENABLE_REQ__INIT;
  *message = init_value;
}
size_t ota_update_enable_req__get_packed_size
                     (const OtaUpdateEnableReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_enable_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_update_enable_req__pack
                     (const OtaUpdateEnableReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_enable_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_update_enable_req__pack_to_buffer
                     (const OtaUpdateEnableReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_enable_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaUpdateEnableReq *
       ota_update_enable_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaUpdateEnableReq *)
     protobuf_c_message_unpack (&ota_update_enable_req__descriptor,
                                allocator, len, data);
}
void   ota_update_enable_req__free_unpacked
                     (OtaUpdateEnableReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_enable_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_update_enable_cnf__init
                     (OtaUpdateEnableCnf         *message)
{
  static OtaUpdateEnableCnf init_value = OTA_UPDATE_ENABLE_CNF__INIT;
  *message = init_value;
}
size_t ota_update_enable_cnf__get_packed_size
                     (const OtaUpdateEnableCnf *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_enable_cnf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_update_enable_cnf__pack
                     (const OtaUpdateEnableCnf *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_enable_cnf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_update_enable_cnf__pack_to_buffer
                     (const OtaUpdateEnableCnf *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_enable_cnf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaUpdateEnableCnf *
       ota_update_enable_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaUpdateEnableCnf *)
     protobuf_c_message_unpack (&ota_update_enable_cnf__descriptor,
                                allocator, len, data);
}
void   ota_update_enable_cnf__free_unpacked
                     (OtaUpdateEnableCnf *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_enable_cnf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_update_dl_finished_ind__init
                     (OtaUpdateDlFinishedInd         *message)
{
  static OtaUpdateDlFinishedInd init_value = OTA_UPDATE_DL_FINISHED_IND__INIT;
  *message = init_value;
}
size_t ota_update_dl_finished_ind__get_packed_size
                     (const OtaUpdateDlFinishedInd *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_dl_finished_ind__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_update_dl_finished_ind__pack
                     (const OtaUpdateDlFinishedInd *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_dl_finished_ind__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_update_dl_finished_ind__pack_to_buffer
                     (const OtaUpdateDlFinishedInd *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_dl_finished_ind__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaUpdateDlFinishedInd *
       ota_update_dl_finished_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaUpdateDlFinishedInd *)
     protobuf_c_message_unpack (&ota_update_dl_finished_ind__descriptor,
                                allocator, len, data);
}
void   ota_update_dl_finished_ind__free_unpacked
                     (OtaUpdateDlFinishedInd *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_dl_finished_ind__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_update_apply_image_req__init
                     (OtaUpdateApplyImageReq         *message)
{
  static OtaUpdateApplyImageReq init_value = OTA_UPDATE_APPLY_IMAGE_REQ__INIT;
  *message = init_value;
}
size_t ota_update_apply_image_req__get_packed_size
                     (const OtaUpdateApplyImageReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_apply_image_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_update_apply_image_req__pack
                     (const OtaUpdateApplyImageReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_apply_image_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_update_apply_image_req__pack_to_buffer
                     (const OtaUpdateApplyImageReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_apply_image_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaUpdateApplyImageReq *
       ota_update_apply_image_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaUpdateApplyImageReq *)
     protobuf_c_message_unpack (&ota_update_apply_image_req__descriptor,
                                allocator, len, data);
}
void   ota_update_apply_image_req__free_unpacked
                     (OtaUpdateApplyImageReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ota_update_apply_image_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor address_struct__field_descriptors[5] =
{
  {
    "addrMode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AddressStruct, addrmode),
    &address_mode__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieeeAddr",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    PROTOBUF_C_OFFSETOF(AddressStruct, has_ieeeaddr),
    PROTOBUF_C_OFFSETOF(AddressStruct, ieeeaddr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "groupAddr",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(AddressStruct, has_groupaddr),
    PROTOBUF_C_OFFSETOF(AddressStruct, groupaddr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "broadcaseAddr",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(AddressStruct, has_broadcaseaddr),
    PROTOBUF_C_OFFSETOF(AddressStruct, broadcaseaddr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "endpointID",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(AddressStruct, has_endpointid),
    PROTOBUF_C_OFFSETOF(AddressStruct, endpointid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned address_struct__field_indices_by_name[] = {
  0,   /* field[0] = addrMode */
  3,   /* field[3] = broadcaseAddr */
  4,   /* field[4] = endpointID */
  2,   /* field[2] = groupAddr */
  1,   /* field[1] = ieeeAddr */
};
static const ProtobufCIntRange address_struct__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor address_struct__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "AddressStruct",
  "AddressStruct",
  "AddressStruct",
  "",
  sizeof(AddressStruct),
  5,
  address_struct__field_descriptors,
  address_struct__field_indices_by_name,
  1,  address_struct__number_ranges,
  (ProtobufCMessageInit) address_struct__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const OtaMgrCmdIdT ota_zigbee_generic_cnf__cmd_id__default_value = OTA_MGR_CMD_ID_T__ZIGBEE_GENERIC_CNF;
static const ProtobufCFieldDescriptor ota_zigbee_generic_cnf__field_descriptors[3] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaZigbeeGenericCnf, cmdid),
    &ota_mgr_cmd_id_t__descriptor,
    &ota_zigbee_generic_cnf__cmd_id__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaZigbeeGenericCnf, status),
    &generic_status__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequenceNumber",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(OtaZigbeeGenericCnf, has_sequencenumber),
    PROTOBUF_C_OFFSETOF(OtaZigbeeGenericCnf, sequencenumber),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_zigbee_generic_cnf__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  2,   /* field[2] = sequenceNumber */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ota_zigbee_generic_cnf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ota_zigbee_generic_cnf__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OtaZigbeeGenericCnf",
  "OtaZigbeeGenericCnf",
  "OtaZigbeeGenericCnf",
  "",
  sizeof(OtaZigbeeGenericCnf),
  3,
  ota_zigbee_generic_cnf__field_descriptors,
  ota_zigbee_generic_cnf__field_indices_by_name,
  1,  ota_zigbee_generic_cnf__number_ranges,
  (ProtobufCMessageInit) ota_zigbee_generic_cnf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const OtaMgrCmdIdT ota_zigbee_generic_rsp_ind__cmd_id__default_value = OTA_MGR_CMD_ID_T__ZIGBEE_GENERIC_RSP_IND;
static const ProtobufCFieldDescriptor ota_zigbee_generic_rsp_ind__field_descriptors[3] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaZigbeeGenericRspInd, cmdid),
    &ota_mgr_cmd_id_t__descriptor,
    &ota_zigbee_generic_rsp_ind__cmd_id__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequenceNumber",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaZigbeeGenericRspInd, sequencenumber),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaZigbeeGenericRspInd, status),
    &generic_status__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_zigbee_generic_rsp_ind__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  1,   /* field[1] = sequenceNumber */
  2,   /* field[2] = status */
};
static const ProtobufCIntRange ota_zigbee_generic_rsp_ind__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ota_zigbee_generic_rsp_ind__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OtaZigbeeGenericRspInd",
  "OtaZigbeeGenericRspInd",
  "OtaZigbeeGenericRspInd",
  "",
  sizeof(OtaZigbeeGenericRspInd),
  3,
  ota_zigbee_generic_rsp_ind__field_descriptors,
  ota_zigbee_generic_rsp_ind__field_indices_by_name,
  1,  ota_zigbee_generic_rsp_ind__number_ranges,
  (ProtobufCMessageInit) ota_zigbee_generic_rsp_ind__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const OtaMgrCmdIdT ota_update_image_registeration_req__cmd_id__default_value = OTA_MGR_CMD_ID_T__OTA_UPDATE_IMAGE_REGISTERATION_REQ;
static const ProtobufCFieldDescriptor ota_update_image_registeration_req__field_descriptors[9] =
{
  {
    "cmdID",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, cmdid),
    &ota_mgr_cmd_id_t__descriptor,
    &ota_update_image_registeration_req__cmd_id__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imagePath",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, imagepath),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "registerUnregister",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, registerunregister),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "executeTiming",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, executetiming),
    &ota_execute_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "executionDelay",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, has_executiondelay),
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, executiondelay),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "executionTime",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, has_executiontime),
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, executiontime),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "updateSupportedDeviceList",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, updatesupporteddevicelist),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supportedDeviceList",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FIXED64,
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, n_supporteddevicelist),
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, supporteddevicelist),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notification",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateImageRegisterationReq, notification),
    &ota_notification_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_update_image_registeration_req__field_indices_by_name[] = {
  0,   /* field[0] = cmdID */
  3,   /* field[3] = executeTiming */
  4,   /* field[4] = executionDelay */
  5,   /* field[5] = executionTime */
  1,   /* field[1] = imagePath */
  8,   /* field[8] = notification */
  2,   /* field[2] = registerUnregister */
  7,   /* field[7] = supportedDeviceList */
  6,   /* field[6] = updateSupportedDeviceList */
};
static const ProtobufCIntRange ota_update_image_registeration_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor ota_update_image_registeration_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OtaUpdateImageRegisterationReq",
  "OtaUpdateImageRegisterationReq",
  "OtaUpdateImageRegisterationReq",
  "",
  sizeof(OtaUpdateImageRegisterationReq),
  9,
  ota_update_image_registeration_req__field_descriptors,
  ota_update_image_registeration_req__field_indices_by_name,
  1,  ota_update_image_registeration_req__number_ranges,
  (ProtobufCMessageInit) ota_update_image_registeration_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const OtaMgrCmdIdT ota_update_enable_req__cmd_id__default_value = OTA_MGR_CMD_ID_T__OTA_UPDATE_ENABLE_REQ;
static const ProtobufCFieldDescriptor ota_update_enable_req__field_descriptors[2] =
{
  {
    "cmdID",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateEnableReq, cmdid),
    &ota_mgr_cmd_id_t__descriptor,
    &ota_update_enable_req__cmd_id__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateEnableReq, mode),
    &ota_enable_modes__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_update_enable_req__field_indices_by_name[] = {
  0,   /* field[0] = cmdID */
  1,   /* field[1] = mode */
};
static const ProtobufCIntRange ota_update_enable_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ota_update_enable_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OtaUpdateEnableReq",
  "OtaUpdateEnableReq",
  "OtaUpdateEnableReq",
  "",
  sizeof(OtaUpdateEnableReq),
  2,
  ota_update_enable_req__field_descriptors,
  ota_update_enable_req__field_indices_by_name,
  1,  ota_update_enable_req__number_ranges,
  (ProtobufCMessageInit) ota_update_enable_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const OtaMgrCmdIdT ota_update_enable_cnf__cmd_id__default_value = OTA_MGR_CMD_ID_T__OTA_UPDATE_ENABLE_CNF;
static const ProtobufCFieldDescriptor ota_update_enable_cnf__field_descriptors[2] =
{
  {
    "cmdID",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateEnableCnf, cmdid),
    &ota_mgr_cmd_id_t__descriptor,
    &ota_update_enable_cnf__cmd_id__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateEnableCnf, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_update_enable_cnf__field_indices_by_name[] = {
  0,   /* field[0] = cmdID */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ota_update_enable_cnf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ota_update_enable_cnf__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OtaUpdateEnableCnf",
  "OtaUpdateEnableCnf",
  "OtaUpdateEnableCnf",
  "",
  sizeof(OtaUpdateEnableCnf),
  2,
  ota_update_enable_cnf__field_descriptors,
  ota_update_enable_cnf__field_indices_by_name,
  1,  ota_update_enable_cnf__number_ranges,
  (ProtobufCMessageInit) ota_update_enable_cnf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const OtaMgrCmdIdT ota_update_dl_finished_ind__cmd_id__default_value = OTA_MGR_CMD_ID_T__OTA_UPDATE_DL_FINISHED_IND;
static const ProtobufCFieldDescriptor ota_update_dl_finished_ind__field_descriptors[3] =
{
  {
    "cmdID",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateDlFinishedInd, cmdid),
    &ota_mgr_cmd_id_t__descriptor,
    &ota_update_dl_finished_ind__cmd_id__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateDlFinishedInd, status),
    &ota_status__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateDlFinishedInd, address),
    &address_struct__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_update_dl_finished_ind__field_indices_by_name[] = {
  2,   /* field[2] = address */
  0,   /* field[0] = cmdID */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ota_update_dl_finished_ind__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ota_update_dl_finished_ind__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OtaUpdateDlFinishedInd",
  "OtaUpdateDlFinishedInd",
  "OtaUpdateDlFinishedInd",
  "",
  sizeof(OtaUpdateDlFinishedInd),
  3,
  ota_update_dl_finished_ind__field_descriptors,
  ota_update_dl_finished_ind__field_indices_by_name,
  1,  ota_update_dl_finished_ind__number_ranges,
  (ProtobufCMessageInit) ota_update_dl_finished_ind__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const OtaMgrCmdIdT ota_update_apply_image_req__cmd_id__default_value = OTA_MGR_CMD_ID_T__OTA_UPDATE_ENABLE_REQ;
static const ProtobufCFieldDescriptor ota_update_apply_image_req__field_descriptors[2] =
{
  {
    "cmdID",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateApplyImageReq, cmdid),
    &ota_mgr_cmd_id_t__descriptor,
    &ota_update_apply_image_req__cmd_id__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtaUpdateApplyImageReq, address),
    &address_struct__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_update_apply_image_req__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = cmdID */
};
static const ProtobufCIntRange ota_update_apply_image_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ota_update_apply_image_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OtaUpdateApplyImageReq",
  "OtaUpdateApplyImageReq",
  "OtaUpdateApplyImageReq",
  "",
  sizeof(OtaUpdateApplyImageReq),
  2,
  ota_update_apply_image_req__field_descriptors,
  ota_update_apply_image_req__field_indices_by_name,
  1,  ota_update_apply_image_req__number_ranges,
  (ProtobufCMessageInit) ota_update_apply_image_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue zstack_otasys_ids__enum_values_by_number[1] =
{
  { "RPC_SYS_PB_OTA_MGR", "ZSTACK_OTASYS_IDS__RPC_SYS_PB_OTA_MGR", 20 },
};
static const ProtobufCIntRange zstack_otasys_ids__value_ranges[] = {
{20, 0},{0, 1}
};
const ProtobufCEnumValueIndex zstack_otasys_ids__enum_values_by_name[1] =
{
  { "RPC_SYS_PB_OTA_MGR", 0 },
};
const ProtobufCEnumDescriptor zstack_otasys_ids__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "ZStackOTASysIDs",
  "ZStackOTASysIDs",
  "ZStackOTASysIDs",
  "",
  1,
  zstack_otasys_ids__enum_values_by_number,
  1,
  zstack_otasys_ids__enum_values_by_name,
  1,
  zstack_otasys_ids__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue ota_mgr_cmd_id_t__enum_values_by_number[7] =
{
  { "ZIGBEE_GENERIC_CNF", "OTA_MGR_CMD_ID_T__ZIGBEE_GENERIC_CNF", 0 },
  { "ZIGBEE_GENERIC_RSP_IND", "OTA_MGR_CMD_ID_T__ZIGBEE_GENERIC_RSP_IND", 1 },
  { "OTA_UPDATE_IMAGE_REGISTERATION_REQ", "OTA_MGR_CMD_ID_T__OTA_UPDATE_IMAGE_REGISTERATION_REQ", 2 },
  { "OTA_UPDATE_ENABLE_REQ", "OTA_MGR_CMD_ID_T__OTA_UPDATE_ENABLE_REQ", 3 },
  { "OTA_UPDATE_ENABLE_CNF", "OTA_MGR_CMD_ID_T__OTA_UPDATE_ENABLE_CNF", 4 },
  { "OTA_UPDATE_DL_FINISHED_IND", "OTA_MGR_CMD_ID_T__OTA_UPDATE_DL_FINISHED_IND", 5 },
  { "OTA_UPDATE_APPLY_IMAGE_REQ", "OTA_MGR_CMD_ID_T__OTA_UPDATE_APPLY_IMAGE_REQ", 6 },
};
static const ProtobufCIntRange ota_mgr_cmd_id_t__value_ranges[] = {
{0, 0},{0, 7}
};
const ProtobufCEnumValueIndex ota_mgr_cmd_id_t__enum_values_by_name[7] =
{
  { "OTA_UPDATE_APPLY_IMAGE_REQ", 6 },
  { "OTA_UPDATE_DL_FINISHED_IND", 5 },
  { "OTA_UPDATE_ENABLE_CNF", 4 },
  { "OTA_UPDATE_ENABLE_REQ", 3 },
  { "OTA_UPDATE_IMAGE_REGISTERATION_REQ", 2 },
  { "ZIGBEE_GENERIC_CNF", 0 },
  { "ZIGBEE_GENERIC_RSP_IND", 1 },
};
const ProtobufCEnumDescriptor ota_mgr_cmd_id_t__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "otaMgrCmdId_t",
  "otaMgrCmdId_t",
  "OtaMgrCmdIdT",
  "",
  7,
  ota_mgr_cmd_id_t__enum_values_by_number,
  7,
  ota_mgr_cmd_id_t__enum_values_by_name,
  1,
  ota_mgr_cmd_id_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue address_mode__enum_values_by_number[4] =
{
  { "UNICAST", "ADDRESS_MODE__UNICAST", 0 },
  { "GROUPCAST", "ADDRESS_MODE__GROUPCAST", 1 },
  { "BROADCAST", "ADDRESS_MODE__BROADCAST", 2 },
  { "SELF", "ADDRESS_MODE__SELF", 3 },
};
static const ProtobufCIntRange address_mode__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex address_mode__enum_values_by_name[4] =
{
  { "BROADCAST", 2 },
  { "GROUPCAST", 1 },
  { "SELF", 3 },
  { "UNICAST", 0 },
};
const ProtobufCEnumDescriptor address_mode__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "AddressMode",
  "AddressMode",
  "AddressMode",
  "",
  4,
  address_mode__enum_values_by_number,
  4,
  address_mode__enum_values_by_name,
  1,
  address_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue generic_status__enum_values_by_number[2] =
{
  { "SUCCESS", "GENERIC_STATUS__SUCCESS", 0 },
  { "FAILURE", "GENERIC_STATUS__FAILURE", 1 },
};
static const ProtobufCIntRange generic_status__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex generic_status__enum_values_by_name[2] =
{
  { "FAILURE", 1 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor generic_status__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "genericStatus",
  "genericStatus",
  "GenericStatus",
  "",
  2,
  generic_status__enum_values_by_number,
  2,
  generic_status__enum_values_by_name,
  1,
  generic_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue ota_status__enum_values_by_number[4] =
{
  { "OTA_SUCCESS", "OTA_STATUS__OTA_SUCCESS", 0 },
  { "INVALID_IMAGE", "OTA_STATUS__INVALID_IMAGE", 1 },
  { "REQUIRE_MORE_IMAGE", "OTA_STATUS__REQUIRE_MORE_IMAGE", 2 },
  { "ABORT", "OTA_STATUS__ABORT", 3 },
};
static const ProtobufCIntRange ota_status__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex ota_status__enum_values_by_name[4] =
{
  { "ABORT", 3 },
  { "INVALID_IMAGE", 1 },
  { "OTA_SUCCESS", 0 },
  { "REQUIRE_MORE_IMAGE", 2 },
};
const ProtobufCEnumDescriptor ota_status__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "OtaStatus",
  "OtaStatus",
  "OtaStatus",
  "",
  4,
  ota_status__enum_values_by_number,
  4,
  ota_status__enum_values_by_name,
  1,
  ota_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue ota_execute_type__enum_values_by_number[5] =
{
  { "IMMEDIATE", "OTA_EXECUTE_TYPE__IMMEDIATE", 0 },
  { "DELAY", "OTA_EXECUTE_TYPE__DELAY", 1 },
  { "TIME", "OTA_EXECUTE_TYPE__TIME", 2 },
  { "HOLD", "OTA_EXECUTE_TYPE__HOLD", 3 },
  { "NO_CHANGE", "OTA_EXECUTE_TYPE__NO_CHANGE", 255 },
};
static const ProtobufCIntRange ota_execute_type__value_ranges[] = {
{0, 0},{255, 4},{0, 5}
};
const ProtobufCEnumValueIndex ota_execute_type__enum_values_by_name[5] =
{
  { "DELAY", 1 },
  { "HOLD", 3 },
  { "IMMEDIATE", 0 },
  { "NO_CHANGE", 4 },
  { "TIME", 2 },
};
const ProtobufCEnumDescriptor ota_execute_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "OtaExecuteType",
  "OtaExecuteType",
  "OtaExecuteType",
  "",
  5,
  ota_execute_type__enum_values_by_number,
  5,
  ota_execute_type__enum_values_by_name,
  2,
  ota_execute_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue ota_notification_type__enum_values_by_number[3] =
{
  { "DO_NOT_SEND", "OTA_NOTIFICATION_TYPE__DO_NOT_SEND", 0 },
  { "BROADCAST_NOT", "OTA_NOTIFICATION_TYPE__BROADCAST_NOT", 1 },
  { "UNICAST_NOT", "OTA_NOTIFICATION_TYPE__UNICAST_NOT", 2 },
};
static const ProtobufCIntRange ota_notification_type__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex ota_notification_type__enum_values_by_name[3] =
{
  { "BROADCAST_NOT", 1 },
  { "DO_NOT_SEND", 0 },
  { "UNICAST_NOT", 2 },
};
const ProtobufCEnumDescriptor ota_notification_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "OtaNotificationType",
  "OtaNotificationType",
  "OtaNotificationType",
  "",
  3,
  ota_notification_type__enum_values_by_number,
  3,
  ota_notification_type__enum_values_by_name,
  1,
  ota_notification_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue ota_update_cnf_status__enum_values_by_number[4] =
{
  { "UPDATE_SUCCESS", "OTA_UPDATE_CNF_STATUS__UPDATE_SUCCESS", 0 },
  { "BAD_FILE_FORMAT", "OTA_UPDATE_CNF_STATUS__BAD_FILE_FORMAT", 1 },
  { "CANT_UNREGISTER", "OTA_UPDATE_CNF_STATUS__CANT_UNREGISTER", 2 },
  { "OUT_OF_RESOURCES", "OTA_UPDATE_CNF_STATUS__OUT_OF_RESOURCES", 3 },
};
static const ProtobufCIntRange ota_update_cnf_status__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex ota_update_cnf_status__enum_values_by_name[4] =
{
  { "BAD_FILE_FORMAT", 1 },
  { "CANT_UNREGISTER", 2 },
  { "OUT_OF_RESOURCES", 3 },
  { "UPDATE_SUCCESS", 0 },
};
const ProtobufCEnumDescriptor ota_update_cnf_status__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "OtaUpdateCnfStatus",
  "OtaUpdateCnfStatus",
  "OtaUpdateCnfStatus",
  "",
  4,
  ota_update_cnf_status__enum_values_by_number,
  4,
  ota_update_cnf_status__enum_values_by_name,
  1,
  ota_update_cnf_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue ota_enable_modes__enum_values_by_number[3] =
{
  { "DOWNLOAD_ENABLE", "OTA_ENABLE_MODES__DOWNLOAD_ENABLE", 0 },
  { "NEW_DOWNLOAD_DISABLE", "OTA_ENABLE_MODES__NEW_DOWNLOAD_DISABLE", 1 },
  { "DOWNLOAD_DISABLE", "OTA_ENABLE_MODES__DOWNLOAD_DISABLE", 2 },
};
static const ProtobufCIntRange ota_enable_modes__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex ota_enable_modes__enum_values_by_name[3] =
{
  { "DOWNLOAD_DISABLE", 2 },
  { "DOWNLOAD_ENABLE", 0 },
  { "NEW_DOWNLOAD_DISABLE", 1 },
};
const ProtobufCEnumDescriptor ota_enable_modes__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "OtaEnableModes",
  "OtaEnableModes",
  "OtaEnableModes",
  "",
  3,
  ota_enable_modes__enum_values_by_number,
  3,
  ota_enable_modes__enum_values_by_name,
  1,
  ota_enable_modes__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
